name = "cloud-notepad"
main = "src/index.js"
compatibility_date = "2022-05-13"

kv_namespaces = [
  { binding = "NOTES", id = "c82bd0e58cb54175a1814542dc82db24" },
  { binding = "SHARE", id = "5318c6461e3743d5b093fc0d8b5dd6d1" }
]